# Generated by Django 3.1.7 on 2021-03-24 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile_tracker', '0003_auto_20210323_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
