# Generated by Django 3.1.7 on 2021-03-24 02:19

from django.db import migrations, models
import django.db.models.deletion
import pile_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('pile_tracker', '0004_auto_20210323_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='pile',
            field=models.ForeignKey(default=pile_tracker.models.Log.pile_in_primary, null=True, on_delete=django.db.models.deletion.CASCADE, to='pile_tracker.pile'),
        ),
    ]
