# Generated by Django 3.1.7 on 2021-03-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pile_tracker', '0005_auto_20210323_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['date']},
        ),
    ]
