# Generated by Django 3.1.7 on 2021-07-16 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pile_tracker', '0006_auto_20210328_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='move_to',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='log',
            name='pile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pile_tracker.pile'),
        ),
    ]
